sudo: required
dist: xenial
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
compile: gcc
install:
  - sudo apt-get install -y attr libattr1 libattr1-dev
script:
  - set -e
  - cmake -DSYS=OFF .
  - make all